version: '3'
services:
# Rails APP Setting
  app:
    container_name: md_rails
    build:
      context: .
      dockerfile: ./docker/rails/Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app
      - ./public:/app/public
      - ./tmp:/app/tmp
      - ./log:/app/log
    depends_on:
      - db
# MySQL Setting
  db:
    container_name: md_mysql
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - ${DB_PORT}:3306
# Nginx setting
  web:
    container_name: md_nginx
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./public:/app/public
      - ./tmp:/app/tmp
      - ./log:/app/log
    ports:
      - ${WEB_HTTP_PORT}:80
      - ${WEB_HTTPS_PORT}:443
    depends_on:
      - app
volumes:
  db-data: