default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'docmd' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'docpass' } %>
  host: db

production:
  <<: *default
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test